apiVersion: apps/v1
kind: Deployment
metadata:
  name: testovidiu
  labels:
    app: testovidiu
  namespace: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testovidiu
  template:
    metadata:
      labels:
        app: testovidiu
    spec:
      containers:
        - name: testovidiu
          image: sslovidiu.azurecr.io/image-workflow-1700911275991:latest
          ports:
            - containerPort: 8080