apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc
  labels:
    app: btc
  namespace: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc
  template:
    metadata:
      labels:
        app: btc
    spec:
      containers:
        - name: btc
          image: sslovidiu.azurecr.io/image-workflow-1700910522881:latest
          ports:
            - containerPort: 8080