apiVersion: v1
kind: Service
metadata:
  name: testovidiu
  namespace: bitcoin
spec:
  type: LoadBalancer
  selector:
    app: testovidiu
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080