apiVersion: v1
kind: Service
metadata:
  name: btcmonitor
  namespace: bitcoin
spec:
  type: LoadBalancer
  selector:
    app: btcmonitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080